# Generated by Django 2.0.1 on 2018-08-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, help_text='Introduce your self.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('n', 'Newbie Hacker'), ('j', 'Junior Hacker'), ('s', 'Senior Hacker'), ('p', 'Professional Hacker'), ('w', 'World Class Hacker'), ('g', 'GOD Hacker')], default='n', help_text='Class Level', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
