# Generated by Django 2.0.1 on 2018-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180804_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, help_text='Introduce your self.'),
        ),
    ]
