# Generated by Django 2.0.7 on 2018-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180807_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/default.jpg', upload_to='user/profile_pic'),
        ),
    ]
