# Generated by Django 2.0.1 on 2018-08-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('accounts', '0010_auto_20180807_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_tools',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='tools.Tool'),
        ),
    ]
