# Generated by Django 2.0.1 on 2018-08-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20180807_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_date', models.DateTimeField(auto_now_add=True)),
                ('tool_title', models.CharField(max_length=100)),
                ('tool_contents', models.TextField(blank=True, help_text='Post Contents')),
                ('tool_like', models.PositiveIntegerField(default=0)),
                ('tool_file', models.FileField(null=True, upload_to='tool/')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_contents', models.CharField(max_length=200)),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tools.Tool')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
