# Generated by Django 2.0.7 on 2018-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_post_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
