# Generated by Django 2.0.7 on 2018-08-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20180814_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
